CREATE TABLESPACE TEMPERATURE_DATA datafile '/u01/app/oracle/oradata/ORATEST/datafile/temperature_data01.dbf' size 64m autoextend ON NEXT 64m maxsize 2g;
CREATE USER temperature IDENTIFIED BY temperature DEFAULT TABLESPACE TEMPERATURE_DATA;
  ALTER USER temperature quota unlimited ON TEMPERATURE_DATA;
  GRANT CONNECT TO temperature;
  GRANT RESOURCE TO temperature;
  GRANT CREATE VIEW TO temperature;
  GRANT CREATE materialized VIEW TO temperature;
  CREATE TABLE TEMPERATURE.COUNTRY
    (
      IDCOUNTRY NUMBER GENERATED ALWAYS AS IDENTITY,
      COUNTRY   VARCHAR2(40),
      CONSTRAINT un_IDCOUNTRY UNIQUE(IDCOUNTRY),
      CONSTRAINT pk_COUNTRY PRIMARY KEY (COUNTRY)
    );
  CREATE TABLE TEMPERATURE.STATE
    (
      IDSTATE NUMBER GENERATED ALWAYS AS IDENTITY,
      STATE     VARCHAR2(40),
      IDCOUNTRY NUMBER NOT NULL,
      CONSTRAINT un_IDSTATE UNIQUE(IDSTATE),
      CONSTRAINT pk_STATE PRIMARY KEY (STATE,IDCOUNTRY),
      CONSTRAINT fk_STATE_COUNTRY FOREIGN KEY (IDCOUNTRY) REFERENCES TEMPERATURE.COUNTRY(IDCOUNTRY)
    );
  CREATE TABLE TEMPERATURE.CITY
    (
      IDCITY    NUMBER GENERATED ALWAYS AS IDENTITY,
      CITY      VARCHAR2(30),
      IDCOUNTRY NUMBER NOT NULL,
      LATITUDE  NUMBER(11,7),
      LONGITUDE NUMBER(11,7),
      CONSTRAINT un_IDCITY UNIQUE(IDCITY),
      CONSTRAINT pk_CITY PRIMARY KEY (CITY, IDCOUNTRY,LATITUDE,LONGITUDE),
      CONSTRAINT fk_CITY_COUNTRY FOREIGN KEY (IDCOUNTRY) REFERENCES TEMPERATURE.COUNTRY(IDCOUNTRY)
    );
  CREATE TABLE TEMPERATURE.TEMP_CITY
    (
      IDTEMPCITY  NUMBER GENERATED ALWAYS AS IDENTITY,
      DATA        DATE,
      TEMPERATURE NUMBER(10,6),
      ERROR       NUMBER(10,6),
      IDCITY      NUMBER NOT NULL,
      CONSTRAINT un_IDTEMPCITY UNIQUE(IDTEMPCITY),
      CONSTRAINT pk_TEMPCITY PRIMARY KEY (DATA, IDCITY),
      CONSTRAINT fk_TEMPCITY_CITY FOREIGN KEY (IDCITY) REFERENCES TEMPERATURE.CITY(IDCITY)
    );
  CREATE TABLE TEMPERATURE.TEMP_MAJ_CITY
    (
      IDTEMPMAJCITY NUMBER GENERATED ALWAYS AS IDENTITY,
      DATA          DATE,
      TEMPERATURE   NUMBER(10,6),
      ERROR         NUMBER(10,6),
      IDCITY        NUMBER NOT NULL,
      CONSTRAINT un_IDTEMPMAJCITY UNIQUE(IDTEMPMAJCITY),
      CONSTRAINT pk_TEMPMAJCITY PRIMARY KEY (DATA, IDCITY),
      CONSTRAINT fk_TEMPMAJCITY_CITY FOREIGN KEY (IDCITY) REFERENCES TEMPERATURE.CITY(IDCITY)
    );
  CREATE TABLE TEMPERATURE.TEMP_COUNTRY
    (
      IDTEMPCOUNTRY NUMBER GENERATED ALWAYS AS IDENTITY,
      DATA          DATE,
      TEMPERATURE   NUMBER(10,6),
      ERROR         NUMBER(10,6),
      IDCOUNTRY     NUMBER NOT NULL,
      CONSTRAINT un_IDTEMPCOUNTRY UNIQUE(IDTEMPCOUNTRY),
      CONSTRAINT pk_TEMPCOUNTRY PRIMARY KEY (DATA, IDCOUNTRY),
      CONSTRAINT fk_TEMPCOUNTRY_COUNTRY FOREIGN KEY (IDCOUNTRY) REFERENCES TEMPERATURE.COUNTRY(IDCOUNTRY)
    );
  CREATE TABLE TEMPERATURE.TEMP_STATE
    (
      IDTEMPSTATE NUMBER GENERATED ALWAYS AS IDENTITY,
      DATA        DATE,
      TEMPERATURE NUMBER(10,6),
      ERROR       NUMBER(10,6),
      IDSTATE     NUMBER NOT NULL,
      CONSTRAINT un_IDTEMPSTATE UNIQUE(IDTEMPSTATE),
      CONSTRAINT pk_TEMPSTATE PRIMARY KEY (DATA, IDSTATE),
      CONSTRAINT fk_TEMPSTATE_STATE FOREIGN KEY (IDSTATE) REFERENCES TEMPERATURE.STATE(IDSTATE)
    );

