-- Query utili da eseguire con l'utente TEMPERATURE


--Ricava media annuale, media dei massimi annuali e media dei minimi annuali

SELECT 
COUNTRY,
ROUND(AVG(MEDIA_ANNO),2) MEDIA
,ROUND(AVG(MAX_ANNO),2) MASSIMO
,ROUND(AVG(MIN_ANNO),2) MINIMO
FROM 
(SELECT
c.country COUNTRY
, AVG(TEMPERATURE) MEDIA_ANNO
, MAX(TEMPERATURE) MAX_ANNO
, MIN(TEMPERATURE) MIN_ANNO
FROM TEMP_COUNTRY t JOIN COUNTRY c ON t.IDCOUNTRY=c.IDCOUNTRY
WHERE t.TEMPERATURE IS NOT NULL
GROUP BY c.country, EXTRACT(YEAR FROM t.data)
HAVING count(*)>11
) a
GROUP BY a.COUNTRY;